### PR TITLE
Update Paint dependency to 2.0.3 and start to modernise build

### PR DESCRIPTION
**Pull request by jdickey**
Paint 0.8.4 is getting rather long in the tooth and several Gem API
changes have necessitated an update; in my opinion, the Gemspec should
reflect that ancient versions are no longer supported.

Also:

* Added Minitest and Rake as explicit development dependencies in Gemspec;
* Added `Gemfile` so `bundle install` can find Gemspec;
* We now have a (brief) `Gemfile.lock` stating exactly what was used to bundle the Gem;
* All tests still pass.

### CODE REVIEW

**Comment by jdickey** [comment]
Will rework and resubmit.

**Comment by vivien** [comment]
Thanks for taking care of this!

**Comment by jdickey** [comment]
Sorry it dropped off the table the last couple weeks; I should have a new PR put together this coming week.

**Comment by vivien** [comment]
It may be a good opportunity to switch to Ruby 2.6 / Bundler 2.0?

**Comment by jdickey** [comment]
That sounds like a great idea, as soon as I can sit someplace other than the throne for a few hours 🤢

**Pull request closed without merging**
